name: Train Neural Network

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.9'
    - name: Install Libraries
      run: pip install pandas numpy scikit-learn
    - name: Run Training
      run: python train_model.py
